[package]
name = "virtualization"
version = "0.0.1"
authors = ["Wojciech Kluczka <wojciech.kluczka@gmail.com>"]

[dependencies]
vnc = "0.4"
dharma = "0.1"
timber = "0.1"
cognitive-qualia = "0.1"
cognitive-inputs = "0.1"

[lib]
name = "virtualization"
path = "lib.rs"
